# Generated by Django 4.2.7 on 2023-11-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekut_env', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='new',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='official',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
