# Generated by Django 4.2.7 on 2023-11-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekut_env', '0002_official_new_official_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='new',
            new_name='pic',
        ),
    ]
